export const GET_OBSERVATIONS = 'GET_OBSERVATIONS'
export const ADD_OBSERVATION = 'ADD_OBSERVATION'
export const OBSERVATIONS_LOADING = 'OBSERVATIONS_LOADING'
export const SORT_OBSERVATIONS = 'SORT_OBSERVATIONS'
